version: '3.8'

services:
  db:
    image: postgres:15.3-alpine
    restart: always
    environment:
      POSTGRES_DB: productDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - product-data:/var/lib/postgresql/data
  product-service:
      build:
        context: .
        dockerfile: Dockerfile
      restart: always
      ports:
        - '8080:8080'
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/productDB
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: postgres
      depends_on:
        - db

volumes:
  product-data:
