version: '3.8'

services:
  db-cart:
    image: postgres:15.3-alpine
    restart: always
    environment:
      POSTGRES_DB: cartDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5433:5432'
    volumes:
      - cart-data:/var/lib/postgresql/data

  cart-service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8081:8081'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-cart:5432/cartDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db-cart

volumes:
  cart-data:
